name: Package Application with Pyinstaller

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Build dependencies
      run: pip install -r requirements.txt -r requirements.windows.txt -r requirements.build.txt

    - name: Build
      run: make build-exe

    - name: Add File to release
      uses: softprops/action-gh-release@v1
      with:
        files: src/dist/windows/send_ardis.exe
