name: Package Application with Pyinstaller

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        architecture: 'x86'

    - name: Install Pipenv
      run: pip install pipenv

    - name: Install Python Libs
      run: pipenv update --dev

    - name: Build
      run: pipenv run build-exe

    - name: Add File to release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/tx-mes-cli.exe
