name: Package Application with Pyinstaller

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: PyInstaller Windows
      # You may pin to the exact commit or the version.
      # uses: JackMcKew/pyinstaller-action-windows@a8dee21ad01bbc7e7363d445bb632691b95ba057
      uses: GaNiziolek/pyinstaller-action-windows@2b9cb332b6b2ab7c47890dd7489d84ede9f38216
      with:
        # Directory containing source code (optional requirements.txt).
        path: src

    - name: Add File to release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          src/dist/windows/send_ardis.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
